# Generated by Django 3.2 on 2021-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210629_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hreviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/')),
                ('nickname', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mreviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review/')),
                ('nickname', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
