# Generated by Django 3.2 on 2021-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210629_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hreviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hreview/'),
        ),
        migrations.AlterField(
            model_name='mreviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mreview/'),
        ),
    ]
